using System;

// IMPORTANT: THIS IS AN AUTOGENERATED FILE CREATED BY THE RAPTOR PLUGIN UTILITY
// THIS FILE WILL BE OVERWRITTEN EVERY TIME THE PLUGIN IS BUILT. DO NOT WRITE CODE IN THIS FILE, AS IT WILL BE OVERWRITTEN
// Instead, you should use the non-autogenerated file in the same folder.

namespace RomanPort.ViewRdsBar
{
    public partial class ViewRdsBarPlugin
    {
        
        // DO NOT EDIT THESE SETTINGS. THEY WILL NOT BE APPLIED AND WILL BE OVERWRITTEN.
        // Instead, edit them in ../config.json

        public override string DeveloperName => "RomanPort";
        public override string PluginName => "ViewRdsBar";
        public override Guid PluginUuid => Guid.Parse("8e3ceb7b-c929-4191-83f8-ab2268dd7c2c");
        public override ushort VersionMajor => 0;
        public override ushort VersionMinor => 0;
        public override ushort VersionBuild => 47;
        public override uint SdkVersion => 5;

    }
}
