using System;

// IMPORTANT: THIS IS AN AUTOGENERATED FILE CREATED BY THE RAPTOR PLUGIN UTILITY
// THIS FILE WILL BE OVERWRITTEN EVERY TIME THE PLUGIN IS BUILT. DO NOT WRITE CODE IN THIS FILE, AS IT WILL BE OVERWRITTEN
// Instead, you should use the non-autogenerated file in the same folder.

namespace RomanPort.SourceFile
{
    public partial class SourceFilePlugin
    {
        
        // DO NOT EDIT THESE SETTINGS. THEY WILL NOT BE APPLIED AND WILL BE OVERWRITTEN.
        // Instead, edit them in ../config.json

        public override string DeveloperName => "RomanPort";
        public override string PluginName => "SourceFile";
        public override Guid PluginUuid => Guid.Parse("2838d863-c177-46a9-9604-67d1060950c3");
        public override ushort VersionMajor => 0;
        public override ushort VersionMinor => 0;
        public override ushort VersionBuild => 8;
        public override uint SdkVersion => 5;

    }
}
