using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace RaptorPluginUtil.Util
{
    public static class CSharpFileUtil
    {
        public static void WriteAutogeneratedFile(RaptorConfig cfg)
        {
            //Create template
            string data = TemplateUtil.LoadTemplate("CsTemplates.autogen.txt", new Dictionary<string, string>
            {
                {"NAMESPACE", $"{cfg.developer_name}.{cfg.plugin_name}" },
                {"CLASS_NAME", $"{cfg.plugin_name}Plugin" },
                {"DEVELOPER_NAME", cfg.developer_name },
                {"PLUGIN_NAME", cfg.plugin_name },
                {"PLUGIN_UUID", cfg.plugin_uuid },
                {"VERSION_MAJOR", cfg.version_major.ToString() },
                {"VERSION_MINOR", cfg.version_minor.ToString() },
                {"VERSION_BUILD", cfg.version_build.ToString() },
                {"SDK_VERSION", Program.VERSION_CODE.ToString() }
            });

            //Write
            File.WriteAllText($"server/{cfg.plugin_name}PluginInfo.cs", data);
        }

        public static void WriteDefaultFile(RaptorConfig cfg)
        {
            //Create template
            string data = TemplateUtil.LoadTemplate("CsTemplates.main.txt", new Dictionary<string, string>
            {
                {"NAMESPACE", $"{cfg.developer_name}.{cfg.plugin_name}" },
                {"CLASS_NAME", $"{cfg.plugin_name}Plugin" }
            });

            //Write
            File.WriteAllText($"server/{cfg.plugin_name}Plugin.cs", data);
        }
    }
}
